# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Applications/CMake.app/Contents/share/cmake-3.28/Modules/WriteBasicConfigVersionFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/david-tylerighedosa/Documents/CSCE441/glfw-3.3.9/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/david-tylerighedosa/Documents/CSCE441/glfw-3.3.9/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/david-tylerighedosa/Documents/CSCE441/glfw-3.3.9/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/david-tylerighedosa/Documents/CSCE441/glfw-3.3.9/src/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/david-tylerighedosa/Documents/CSCE441/glfw-3.3.9/src/glfw3Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/david-tylerighedosa/Documents/CSCE441/glfw-3.3.9/src/glfw_config.h.in))

/Users/david-tylerighedosa/Desktop/231008755/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -S/Users/david-tylerighedosa/Desktop/231008755 -B/Users/david-tylerighedosa/Desktop/231008755/build
